server:
  port: 6689
spring:
  application:
    name: security-jwt
  datasource:
    #url: jdbc:mysql://localhost:3307/security_jwt
    url: jdbc:postgresql://localhost:5432/security_jwt
    #url: jdbc:mysql://localhost/security_jwt?autoReconnect=true
    #username: yascode
    username: postgres
    #username: config
    #password: yascode
    password: YassMel97
    #password: config
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  security:
    jwt:
      algorithm: HS256
      secret_key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 240000
      not_before: 1200
      cookie_name: jwt_cookie
      refresh_token:
        expiration: 1296000000
        cookie_name: refresh_jwt_cookie
    user:
      magic:
        username: RFvHrEhe
        password: $2a$10$zN7fSt9ILv.ptLKkpI29x.BW6RBfjZG33AvO7kW.ep1eKFXFBOwpq
        role: ADMIN
        refresh_token:
          value: RDMyOWFRWVBvdFZxZkY3b21aQk84M0xnR2tlTmJ3SjQ=
          expiration: 86400

