server:
  port: 6689
  env:
    address: localhost
    request-protocol: http
    description: dev
spring:
  application:
    name: security-jwt
  datasource:
    url: jdbc:postgresql://192.168.214.108:5432/banking_db
    username: banking
    password: 834xQqztIANjmqI7R2eBmgUT
    driver-class-name: org.postgresql.Driver
    #url: jdbc:mysql://localhost:3307/security_jwt
    #url: jdbc:postgresql://localhost:5432/security_jwt
    #username: yascode
    #username: config
    #password: yascode
    #password: config
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: TRACE
management:
  endpoints:
    web:
      exposure:
        include: "*"
application:
  security:
    jwt:
      algorithm: HS256
      secret_key: 586B633834416E396D7436753879382F423F4428482B4C6250655367566B5970
      expiration: 9000000
      not_before: 1200
      cookie_name: jwt_cookie
      refresh_token:
        expiration: 1296000000
        cookie_name: refresh_jwt_cookie
    user:
      magic:
        username: RFvHrEhe
        password: $2a$10$zN7fSt9ILv.ptLKkpI29x.BW6RBfjZG33AvO7kW.ep1eKFXFBOwpq
        role: MAGIC
        refresh_token:
          value: RDMyOWFRWVBvdFZxZkY3b21aQk84M0xnR2tlTmJ3SjQ=
contact:
  name: Yassin MELLOUKI
  email: yassin.mellouki.j@gmail.com
info:
  title: Bank account management
  version: 0.0.1-SNAPSHOT
  description: Application for managing bank accounts
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

